name : Simple Python CI
on:(push)

jobs:
    build:
            runs-on: ubunu-Latest



               steps:
                 - name: Checkout code
                   user: action/setup-python@v3

                 - name: Set up Python
                   user: action/setup-python@v4
                   with:
                      python-version: "3.9"


                   - name: Install Dependencies
                     run: pip install --upgrade pip


      - name: Run Script
        run: python hello.py
